fix jumping among punctuations #6
cireu/jieba.el pull request #7
Opened 2019-11-14 09:53 UTC by chen-chao

2019-11-15 04:32 UTC, cireu requested changes

2019-11-15 04:32 UTC, cireu commented on jieba.el
> +  (let ((pnt (point)) (beg (point)) (end (point)))
既然下面用`setq`改变了beg和end的值，这里可以先初始化为`nil`

2019-11-15 05:36 UTC, chen-chao commented on jieba.el
> +  (let ((pnt (point)) (beg (point)) (end (point)))
在非中文的时候可以少一个 setq

2019-11-15 05:37 UTC, chen-chao commented on jieba.el
> +  (let ((pnt (point)) (beg (point)) (end (point)))
不过确实有点丑...

2019-11-15 06:24 UTC, cireu approved these changes

2019-11-15 06:25 UTC, cireu commented
感谢贡献！

2019-11-15 06:25 UTC, merged

2019-11-30 10:39 UTC, cireu commented
@chen-chao  今天又想到个更好的思路，先用这个函数跳过标点，然后再正常跳转

```emacs-lisp
(defun jieba--skip-punctuations! (backward?)
  (if backward?
      (while (re-search-backward (rx punct point) nil t))
    (while (re-search-forward (rx point punct) nil t))))
```

2019-12-01 13:53 UTC, chen-chao commented
确实比用 forward-word + backward-word 跳过标点要好. 

之前还有一个改动是对中英文都返回 beg, end, 我觉得比英文返回 nil 要简单一些.